spring:
  application:
    name: item
  cloud: #nacos配置
    nacos:
      discovery:
        server-addr: localhost:8848 #此为nacos地址配置
    gateway:
      routes:
        - id: path_route
          uri: lb://item
          predicates:
            - Path=/item/**
server:
  port: 18081